/**
 * CN attribute -> assigned channel/speaker name.
 *
 * Outputs and inputs use SEPARATE id spaces — the same CN means different
 * things in <OC> and <IC> — so never resolve one against the other's table.
 * Transcribed verbatim from pct6_extract.py (see FINDINGS.md for provenance).
 */

export const OUTPUT_CHANNEL_NAMES: Record<number, string> = {
  0: "Not assigned",
  1: "Front L Full",
  2: "Front R Full",
  3: "Front L High",
  4: "Front R High",
  5: "Front L Mid",
  6: "Front R Mid",
  7: "Front L Low",
  8: "Front R Low",
  9: "Front Center Full",
  10: "Front Center High",
  11: "Front Center Low",
  12: "F Sum",
  13: "Rear L Full",
  14: "Rear R Full",
  15: "Rear L High",
  16: "Rear R High",
  17: "Rear L Mid",
  18: "Rear R Mid",
  19: "Rear L Low",
  20: "Rear R Low",
  21: "Rear Fill Full",
  22: "Rear Fill High",
  23: "Rear Fill Low",
  24: "Rear Sum",
  25: "Subwoofer 1",
  26: "Subwoofer 2",
  27: "Subwoofer 3",
  28: "Subwoofer 4",
  29: "Line Out 1",
  30: "Line Out 2",
  31: "Line Out 3",
  32: "Line Out 4",
  33: "Line Out 5",
  34: "Line Out 6",
  35: "Line Out 7",
  36: "Line Out 8",
  37: "Subwoofer L",
  38: "Subwoofer R",
  39: "Pass Through 1",
  40: "Pass Through 2",
  41: "Pass Through 3",
  42: "Pass Through 4",
  43: "Pass Through 5",
  44: "Pass Through 6",
  45: "Bridge Mode",
  46: "Surround L Full",
  47: "Surround R Full",
  48: "Front Subwoofer L",
  49: "Front Subwoofer R",
  50: "Pass Through 7",
  51: "Pass Through 8",
  52: "Pass Through 9",
  53: "Pass Through 10",
  54: "Pass Through 11",
  55: "Pass Through 12",
  56: "User defined Name",
};

export const INPUT_CHANNEL_NAMES: Record<number, string> = {
  0: "Not assigned",
  1: "Front L Full",
  2: "Front R Full",
  3: "Front L High",
  4: "Front R High",
  5: "Front L Mid",
  6: "Front R Mid",
  7: "Front L Low",
  8: "Front R Low",
  10: "Front Center Full",
  11: "Front Center High",
  12: "Front Center Low",
  13: "F Sum",
  14: "Rear L Full",
  15: "Rear R Full",
  16: "Rear L High",
  17: "Rear R High",
  18: "Rear L Mid",
  19: "Rear R Mid",
  20: "Rear L Low",
  21: "Rear R Low",
  22: "Rear Fill Full",
  23: "Rear Fill High",
  24: "Rear Fill Low",
  25: "R Sum",
  26: "Subwoofer 1",
  27: "Subwoofer 2",
  28: "Subwoofer 3",
  29: "Subwoofer 4",
  30: "Line In 1",
  31: "Line In 2",
  32: "Line In 3",
  33: "Line In 4",
  34: "Line In 5",
  35: "Line In 6",
  36: "Line In 7",
  37: "Line In 8",
  38: "Digital In L",
  39: "Digital In R",
  40: "Opt. In 3",
  41: "Opt. In 4",
  42: "Opt. In 5",
  43: "Opt. In 6",
  44: "Opt. In 7",
  45: "Opt. In 8",
  46: "Opt. Sub 1",
  47: "Opt. Sub 2",
  48: "Opt. Sub 3",
  49: "Opt. Sub 4",
  50: "Opt. Sub 5",
  51: "Opt. Sub 6",
  52: "Opt. Sub 7",
  53: "Opt. Sub 8",
  54: "AUX L",
  55: "AUX R",
  56: "HEC L",
  57: "HEC R",
  58: "MEC L",
  59: "MEC R",
  60: "Front MID",
  61: "Front SIDE",
  62: "Rear MID",
  63: "Rear SIDE",
  64: "AUX2 L",
  65: "AUX2 R",
  66: "ASD Front Left",
  67: "ASD Front Right",
  68: "ASD Rear Left",
  69: "ASD Rear Right",
  70: "Subwoofer L",
  71: "Subwoofer R",
  72: "Surround L Full",
  73: "Surround R Full",
  74: "Front Subwoofer L",
  75: "Front Subwoofer R",
  76: "USB L",
  77: "USB R",
};

/** <Fil T="..."> filter kind. Odd = lowpass, even = highpass; 17 = parametric peak. */
export const FILTER_TYPES: Record<number, [string, string]> = {
  1: ["unused", "unused band"],
  9: ["lowpass", "Lowpass Butterworth"],
  10: ["highpass", "Highpass Butterworth"],
  11: ["lowpass", "Lowpass Bessel"],
  12: ["highpass", "Highpass Bessel"],
  13: ["lowpass", "Lowpass Tschebyscheff"],
  14: ["highpass", "Highpass Tschebyscheff"],
  15: ["lowpass", "Lowpass Linkwitz"],
  16: ["highpass", "Highpass Linkwitz"],
  17: ["peak", "Peak (parametric EQ)"],
};
